<?php

/**
 * @file
 * Generate custom thumbnails for epub media entities.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function media_thumbnails_epub_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.media_thumbnails_epub':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Media Thumbnails EPUB module generates thumbnails for epub media entities.') . '</p>';
      return $output;
  }
}
