<?php

/**
 * @file
 * Define hook implementations for the typogrify module.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function typogrify_migration_plugins_alter(array &$migrations) {
  if (isset($migrations['d6_filter_format'])) {
    $migration = &$migrations['d6_filter_format'];

    // Add 6.x-1.x to 8.x-1.x filter ID mapping.
    $migration['process']['filters']['process']['id']['map']['typogrify'][0] = 'typogrify';
  }
}
