/**
 * @file
 * DO NOT EDIT THIS FILE.
 * JavaScript for the izi message module.
 */

(function ($, Drupal) {
  "use strict";

  Drupal.behaviors.iziMessage = {
    attach: function (context, settings) {
      var messages = context.querySelectorAll('div[data-izi-message]');

      messages.forEach(function (currentValue, currentIndex, listObj) {
        var iziType = currentValue.dataset.type;

        iziToast[iziType](Object.assign(settings.iziMessage, {
          title: currentValue.dataset.title,
          message: currentValue.innerHTML
        }));

        currentValue.remove();
      });

    }
  }
})(jQuery, Drupal);
