<?php

/**
 * @file
 * Provides theme hook implementations for the SDC Component Library module.
 */

/**
 * Defines theme hook implementations for the SDC Component Library module.
 *
 * Implements hook_theme().
 *
 * @param array $existing
 *   An array of existing theme hooks.
 * @param string $type
 *   The type of hook being requested.
 * @param string $theme
 *   The name of the theme.
 * @param string $path
 *   The path to the theme.
 *
 * @return array
 *   An array of theme hook definitions.
 */
function sdc_component_library_theme($existing, $type, $theme, $path) {
  return [
    'component_preview' => [
      'variables' => [
        'components' => [],
      ],
    ],
  ];
}
