<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Implements hook_help().
 */
function path_alias_class_help($section) {
  $output = '';
  switch ($section) {
    case 'admin/help#path_alias_class':
      $output = '<p>' . t('Adds the Path and Path Alias as a class to the body tag on every page.') . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
 
function path_alias_class_preprocess_html(&$variables) {
  $config = \Drupal::config('path_alias_class.settings');
    
  $current_path = \Drupal::service('path.current')->getPath();
  $class_path = str_replace('/', '-', trim($current_path, '/'));
  
  $current_alias = \Drupal::service('path_alias.manager')->getAliasByPath(\Drupal::service('path.current')->getPath());
  $class_alias = str_replace('/', ' ', trim($current_alias, '/'));
  
  // Add a class to the body tag.
  if ($config->get('add_path')) {
    $variables['attributes']['class'][] = $class_path;    
  }
      
  if ($config->get('add_alias')) {
    $variables['attributes']['class'][] = $class_alias;    
  }
  
  $custom_class = $config->get('path_alias_class_custom_class');
  if (!empty($custom_class)) {
    $variables['attributes']['class'][] = $custom_class;
  }
}