<?php

/**
 * @file
 * Primary module hooks for Manage display created node module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function manage_display_node_created_entity_base_field_info_alter(&$base_field_definitions, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'node') {
    $base_field_definitions['created']->setDisplayConfigurable('view', TRUE);
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function manage_display_node_created_theme_registry_alter(&$theme_registry) {
  // Disable the 'inline' versions of node base field templates to workaround
  // https://www.drupal.org/node/2993647.
  unset($theme_registry['field__node__created']);
}

/**
 * Implements hook_module_implements_alter().
 */
function manage_display_node_created_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'entity_base_field_info_alter') {
    // Move to the end of the list.
    $group = $implementations['manage_display_node_created'];
    unset($implementations['manage_display_node_created']);
    $implementations['manage_display_node_created'] = $group;
  }
}
