<?php

/**
 * @file
 * Contains template_generator.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function template_generator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the orejime module.
    case 'help.page.template_generator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 integration of Template Generator') . '</p>';
      return $output;

    default:
      return '';
  }
}

/**
 * Implements hook_entity_insert().
 */
function template_generator_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'entity_view_display' && \Drupal::service('template_generator.manager')
    ->getModeGeneration() === 'display') {
    \Drupal::service('template_generator.manager')
      ->generateTemplate($entity->getTargetEntityTypeId(), $entity->getTargetBundle(), $entity->getMode());
  }
}

/**
 * Implements hook_entity_update().
 */
function template_generator_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'entity_view_display' && \Drupal::service('template_generator.manager')
    ->getModeGeneration() === 'display') {
    \Drupal::service('template_generator.manager')
      ->generateTemplate($entity->getTargetEntityTypeId(), $entity->getTargetBundle(), $entity->getMode());
  }
}
