<?php

/**
 * @file
 * Module file for field_group_settings.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function field_group_settings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the field_group_settings module.
    case 'help.page.field_group_settings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide a field group with toggled visibility.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function field_group_settings_theme() {
  return [
    'field_group_settings' => [
      'render element' => 'element',
      'template' => 'field-group-settings',
      'file' => 'templates/theme.inc',
    ],
  ];
}
