<?php

/**
 * @file
 * Hook implementations and custom functions for the module.
 */

declare(strict_types=1);

use Drupal\cache_pilot\Cache\ApcuCache;
use Drupal\cache_pilot\Hook\Theme\PreprocessCachePilotApcuStatistics;
use Drupal\cache_pilot\Hook\Theme\PreprocessCachePilotOpcacheStatistics;

/**
 * Implements hook_cache_flush().
 */
function cache_pilot_cache_flush(): void {
  $apcu = \Drupal::service(ApcuCache::class);
  $apcu->clear();
}

/**
 * Implements hook_theme().
 */
function cache_pilot_theme(): array {
  return [
    'cache_pilot_apcu_statistics' => [
      'variables' => [
        'statistics' => [],
      ],
    ],
    'cache_pilot_opcache_statistics' => [
      'variables' => [
        'statistics' => [],
      ],
    ],
    'cache_pilot_fragmentation_bar' => [
      'variables' => [
        'fragments' => [],
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_cache_pilot_apcu_statistics(array &$variables): void {
  \Drupal::classResolver(PreprocessCachePilotApcuStatistics::class)($variables);
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_cache_pilot_opcache_statistics(array &$variables): void {
  \Drupal::classResolver(PreprocessCachePilotOpcacheStatistics::class)($variables);
}
