<?php

/**
 * @file
 * Primary module hooks for the Paragraph Block module.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\paragraph_block\Hook\ParagraphBlockHooks;

/**
 * Implements hook_entity_type_alter().
 */
#[LegacyHook]
function paragraph_block_entity_type_alter(array &$entity_types) {
  \Drupal::service(ParagraphBlockHooks::class)->entityTypeAlter($entity_types);
}

/**
 * Implements hook_block_type_form_alter().
 */
#[LegacyHook]
function paragraph_block_block_type_form_alter(array &$form, FormStateInterface &$form_state, string $block_type) {
  \Drupal::service(ParagraphBlockHooks::class)->blockTypeFormAlter($form, $form_state, $block_type);
}

/**
 * Implements hook_form_FORM_ID_form_alter() for 'language_content_settings'.
 */
#[LegacyHook]
function paragraph_block_form_language_content_settings_form_alter(array &$form, FormStateInterface &$form_state, string $block_type) {
  \Drupal::service(ParagraphBlockHooks::class)->formLanguageContentSettingsFormAlter($form, $form_state, $block_type);
}
