<?php

/**
 * @file
 * EPT Call to Action (CTA) module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ept_cta_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ept_cta module.
    case 'help.page.ept_cta':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extra Paragraph Types: Call to Action module provides ability to add Text with CTA button.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function ept_cta_preprocess_paragraph(&$variables) {
  if (empty($variables['elements']['#paragraph']) ||
    $variables['elements']['#paragraph']->bundle() !== 'ept_cta') {
    return;
  }

  $paragraph_class = 'paragraph-id-' . $variables['elements']['#paragraph']->id();
  $ept_settings = $variables['elements']['#paragraph']->field_ept_settings->getValue();

  $service = \Drupal::service('ept_basic_button.generate_custom_css');
  $variables['button_styles'] = $service->generateFromSettings($ept_settings[0]['ept_settings'], $paragraph_class);

  $service = \Drupal::service('ept_cta.generate_cta_css');
  $variables['cta_styles'] = $service->generateFromSettings($ept_settings[0]['ept_settings'], $paragraph_class);
}
