<?php

/**
 * @file
 * Module file for media_folders.
 */

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CloseDialogCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\MessageCommand;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drush\Drush;
use Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem;
use Drupal\Core\Link;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function media_folders_help($route_name, RouteMatchInterface $route_match) : string|\Stringable|array|null {
  switch ($route_name) {
    case 'help.page.media_folders':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides a better UI for managing and selecting Media entities in a folder structure.') . '</p>';
      $output .= '<h3>' . t('Installation') . '</h3>';
      $output .= '<p>' . t('<a href="https://www.drupal.org/documentation/install/modules-themes/modules-8">Normal module installation procedure</a>.') . '</p>';
      $output .= '<h3>' . t('Configuration') . '</h3>';
      $output .= '<p>' . t('Go to "/admin/config/media-folders".') . '</p>';
      $output .= '<h3>' . t('Credits') . '</h3>';
      $output .= '<p>' . t('Powered by <a href="http://javali.pt/">Javali</a>.') . '</p>';
      return $output;

    default:
      return NULL;
  }
}

/**
 * Implements hook_modules_installed().
 *
 * @inheritdoc
 */
function media_folders_modules_installed($modules, $is_syncing) : void {
  if (!$is_syncing && in_array('media_folders', $modules)) {
    $link = Link::fromTextAndUrl(t('click here'), Url::fromRoute('media_folders.sync'));
    \Drupal::messenger()->addStatus(t('To sync all existing media into folders, @link', ['@link' => $link->toString()]));
    if (PHP_SAPI === 'cli' && class_exists('Drush')) {
      try {
        $drush_link = sprintf('<href=%s>%s</>', $link->getUrl()->setAbsolute()->toString(), $link->getText());
        Drush::logger()->notice(dt('To sync all existing media into folders, @link', ['@link' => $drush_link]));
      }
      catch (\Exception $e) {

      }
    }

    $bundles_by_extensions = _media_folders_get_bundles_by_extension();
    if (!empty($bundles_by_extensions) && count(max($bundles_by_extensions)) > 1) {
      $link = Link::fromTextAndUrl(t('settings page'), Url  ::fromRoute('media_folders.configuration'));
      \Drupal::messenger()->addWarning(t('There are media bundles that accept the same file extensions, please handle this in the @link', ['@link' => $link->toString()]));

      if (PHP_SAPI === 'cli' && class_exists('Drush')) {
        try {
          $drush_link = sprintf('<href=%s>%s</>', $link->getUrl()->setAbsolute()->toString(), $link->getText());
          Drush::logger()->warning(dt('There are media bundles that accept the same file extensions, please handle this in the @link', ['@link' => $drush_link]));
        }
        catch (\Exception $e) {

        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 *
 * @inheritdoc
 */
function media_folders_theme() : array {
  return [
    'media_folders_page' => [
      'variables' => [
        'title' => NULL,
        'up_button' => NULL,
        'breadcrumb' => NULL,
        'actions' => NULL,
        'actions_raw' => NULL,
        'buttons' => NULL,
        'form' => NULL,
        'folders' => NULL,
        'navbar' => NULL,
        'class' => NULL,
        'board_class' => NULL,
        'fid' => NULL,
      ],
    ],
    'media_folders_widget' => [
      'variables' => [
        'up_button' => NULL,
        'breadcrumb' => NULL,
        'upload_form' => NULL,
        'form' => NULL,
        'folders' => NULL,
        'navbar' => NULL,
        'class' => NULL,
        'board_class' => NULL,
        'fid' => NULL,
      ],
    ],
    'media_folders_folders' => [
      'variables' => [
        'folders' => NULL,
      ],
    ],
    'media_folders_folder' => [
      'variables' => [
        'icon' => NULL,
        'title' => NULL,
        'weight' => NULL,
        'desc' => NULL,
        'link' => NULL,
        'classes' => NULL,
        'wrapper_classes' => NULL,
        'attr' => NULL,
        'size' => NULL,
        'ftype' => NULL,
        'actions' => NULL,
        'fid' => NULL,
        'uuid' => NULL,
      ],
    ],
    'media_folders_navbar' => [
      'variables' => [
        'folders' => NULL,
      ],
    ],
    'media_folders_load_more' => [
      'variables' => [
        'title' => NULL,
        'link' => NULL,
      ],
    ],
    'media_folders_file_widget' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for file widget template.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: A render element representing the file field widget.
 */
function template_preprocess_media_folders_file_widget(&$variables): void {
  $element = $variables['element'];

  $variables['attributes'] = [
    'class' => [
      'image-widget',
      'js-form-managed-file',
      'form-managed-file',
      'clearfix',
    ],
  ];

  $variables['data'] = [];
  foreach (Element::children($element) as $child) {
    if ($element[$child]['#access']) {
      $variables['data'][$child] = $element[$child];
    }
  }

}

/**
 * Implements hook_entity_base_field_info().
 *
 * @inheritdoc
 */
function media_folders_entity_base_field_info(EntityTypeInterface $entity_type) : array {
  $fields = [];
  if ($entity_type->id() === 'media') {
    $fields['field_folders_folder'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Folder'))
      ->setDescription(t('The ID of the taxonomy term.'))
      ->setSetting('handler', 'default:taxonomy_term')
      ->setSetting('target_type', 'taxonomy_term')
      ->setSetting('handler_settings', [
        'target_bundles' => ['media_folders_folder' => 'media_folders_folder'],
        'auto_create' => FALSE,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'options_select',
        'weight' => 2,
      ]);
  }

  return $fields;
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * @inheritdoc
 */
function media_folders_media_presave(FieldableEntityInterface $entity) : void {
  if ($entity->hasField('field_folders_folder') && !$entity->get('field_folders_folder')->isEmpty()) {
    if ($entity->get('field_folders_folder')->target_id <= 0) {
      $entity->set('field_folders_folder', NULL);
    }
  }
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 *
 * @inheritdoc
 */
function media_folders_field_widget_complete_options_select_form_alter(&$element, FormStateInterface $form_state, $context) : void {
  /** @var \Drupal\Core\Field\EntityReferenceFieldItemList $items */
  $items = $context['items'];

  if ($items->getName() === 'field_folders_folder') {
    $element['widget']['#options']['_none'] = t('Root');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @inheritdoc
 */
function media_folders_form_taxonomy_term_media_folders_folder_form_alter(&$form, FormStateInterface $form_state, $form_id) : void {
  $form['#validate'][] = '_media_folders_validate_term';
}

/**
 * Validate handler for media folder taxonomy term forms.
 *
 * This function validates the taxonomy term form for media folders. It ensures
 * that the folder name is unique within its parent folder by calling the
 * `_media_folders_validate_folder_name` function.
 *
 * @param array $form
 *   The form structure array for the taxonomy term.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object where validation errors will be set.
 */
function _media_folders_validate_term(&$form, FormStateInterface $form_state) : void {
  $values = $form_state->getValues();
  $tid = (!empty($values['tid'])) ? $values['tid'] : NULL;
  _media_folders_validate_folder_name($form_state, $values['parent'], $values['name'][0]['value'], $tid);
}

/**
 * Validates that a folder name is unique within its parent folder.
 *
 * This function checks if a folder with the same name already exists
 * under the specified parent folder. If a duplicate is found, it sets
 * an error on the form state.
 *
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object where validation errors will be set.
 * @param int|string $parent
 *   The ID of the parent folder. Can be 0 for the root folder.
 * @param string $name
 *   The name of the folder to validate.
 * @param int|null $term_id
 *   (Optional) The ID of the current folder term being edited. This is used
 *   to exclude the current folder from the validation check.
 */
function _media_folders_validate_folder_name(&$form_state, $parent, $name, $term_id = NULL) : void {
  $term_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  if (is_array($parent)) {
    $parent = reset($parent);
  }

  if ($parent == 0) {
    $children = $term_storage->loadTree('media_folders_folder', 0, 1, TRUE);
  }
  else {
    $parent_term = $term_storage->load($parent);
    $children = $term_storage->getChildren($parent_term);
  }
  if (!empty($children)) {
    foreach ($children as $child) {
      if (!empty($term_id) && $term_id == $child->id()) {
        continue;
      }
      if (strtolower($child->getName()) == strtolower($name)) {
        $form_state->setErrorByName('name', t('There is already one folder with the same name!'));
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @inheritdoc
 */
function media_folders_form_taxonomy_overview_terms_alter(&$form, FormStateInterface $form_state, $form_id) : void {
  $form['#validate'][] = '_media_folders_validate_overview';
}

/**
 * Validate handler for the media folder file overview form.
 *
 * This function validates the media folder file overview form by ensuring
 * that folder names are unique within their parent folders. If duplicate
 * folder names are found, validation errors are set on the form state.
 *
 * @param array $form
 *   The form structure array for the media folder file overview.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object where validation errors will be set.
 */
function _media_folders_validate_overview(&$form, FormStateInterface $form_state) : void {
  $values = $form_state->getValues();
  $term_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');

  $terms = [];
  foreach ($values['terms'] as $key => $value) {
    $term = $term_storage->load($value['term']['tid']);
    $terms[$value['term']['parent']][$key] = $term->getName();
  }
  foreach ($terms as $values) {
    $duplicates = array_unique(array_diff_assoc($values, array_unique($values)));
    foreach ($duplicates as $key => $value) {
      $form_state->setErrorByName($key, t('There is already one folder with the same name! (@folder)', ['@folder' => $value]));
    }
  }
}

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 *
 * @inheritdoc
 */
function media_folders_ckeditor5_plugin_info_alter(array &$plugin_definitions) : void {
  assert($plugin_definitions['media_library_mediaLibrary'] instanceof CKEditor5PluginDefinition);
  $media_plugin_definition = $plugin_definitions['media_library_mediaLibrary']->toArray();
  $media_plugin_definition['drupal']['class'] = 'Drupal\media_folders\Plugin\CKEditor5Plugin\MediaFolders';
  $plugin_definitions['media_library_mediaLibrary'] = new CKEditor5PluginDefinition($media_plugin_definition);
}

/**
 * Gets all bundles grouped by extensions.
 *
 * @return array
 *   An array of file bundles by extension.
 */
function _media_folders_get_bundles_by_extension() : array {
  $bundles_by_extensions = [];
  $validators = \Drupal::service('media_folders.ui_actions')->getFileValidators();
  foreach ($validators as $bundle => $validator) {
    if (!empty($validator['FileExtension']['extensions'])) {
      $extensions = explode(' ', $validator['FileExtension']['extensions']);
      foreach ($extensions as $value) {
        $bundles_by_extensions[$value][] = $bundle;
      }
    }
  }

  return $bundles_by_extensions;
}

/**
 * Implements hook_field_ui_preconfigured_options_alter().
 *
 * @inheritdoc
 */
function media_folders_field_ui_preconfigured_options_alter(array &$options, $field_type) {
  $class = \Drupal::service('plugin.manager.field.field_type')->getPluginClass($field_type);
  if (!is_a($class, EntityReferenceItem::class, TRUE)) {
    return;
  }

  if (!empty($options['media'])) {
    $options['media']['entity_form_display']['type'] = 'media_folders_widget';
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * @inheritdoc
 */
function media_folders_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'field_ui_preconfigured_options_alter') {
    $group = $implementations['media_folders'];
    unset($implementations['media_folders']);
    $implementations['media_folders'] = $group;
  }
}

/**
 * Implements hook_form_alter().
 *
 * @inheritdoc
 */
function media_folders_form_alter(&$form, FormStateInterface $form_state, $form_id) : void {
  if (!empty($form['field_folders_folder']) && !empty(\Drupal::request()->query->get('media-folders-edit'))) {
    $form_state->disableRedirect();
    $form['errors'] = [
      '#markup' => '<div id="folders-form-errors"></div>',
    ];
    $form['actions']['submit']['#ajax'] = ['callback' => '_media_folders_media_close_modal', 'event' => 'click'];
  }
  if (!empty($form['field_folders_folder']) && !empty(\Drupal::request()->query->get('widget-edit'))) {
    $form['actions']['delete']['#access'] = FALSE;
  }

  if (!empty(\Drupal::request()->query->get('media-folders-delete'))) {
    $form['actions']['cancel']['#ajax'] = ['callback' => '_media_folders_media_delete_close_modal', 'event' => 'click'];
    $form['actions']['submit']['#ajax'] = ['callback' => '_media_folders_media_delete_close_modal', 'event' => 'click'];
  }
}

/**
 * Submit handler for media folder media edit forms.
 *
 * This function closes the modal window on submit.
 *
 * @param array $form
 *   The form structure array for the taxonomy term.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object where validation errors will be set.
 */
function _media_folders_media_close_modal(&$form, FormStateInterface $form_state) {
  $response = new AjaxResponse();

  $errors = $form_state->getErrors();
  if (!empty($errors)) {
    foreach ($errors as $error) {
      $response->addCommand(new MessageCommand($error, '#folders-form-errors', ['type' => 'error']));
    }
    \Drupal::messenger()->deleteAll();
    return $response;
  }

  $folder_value = $form_state->getValue('field_folders_folder');
  $folder = (!empty($folder_value[0]['target_id'])) ? $folder_value[0]['target_id'] : 0;
  $response->addCommand(new CloseDialogCommand('.ui-dialog:has(.media-form) .ui-dialog-content'));
  $response->addCommand(new InvokeCommand('.navbar-folder[data-id=' . $folder . '] a', 'click'));

  return $response;
}

/**
 * Submit handler for media folder media delete forms.
 *
 * This function closes the modal window on submit.
 *
 * @param array $form
 *   The form structure array for the taxonomy term.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object where validation errors will be set.
 */
function _media_folders_media_delete_close_modal(&$form, FormStateInterface $form_state) {
  $response = new AjaxResponse();

  $media = $form_state->getFormObject()->getEntity();
  $folder = (!empty($media->field_folders_folder->target_id)) ? $media->field_folders_folder->target_id : 0;
  $response->addCommand(new CloseDialogCommand('.ui-dialog:has(.media-confirm-form) .ui-dialog-content'));
  $response->addCommand(new InvokeCommand('.navbar-folder[data-id=' . $folder . '] a', 'click'));

  return $response;
}

/**
 * Implements hook_entity_form_display_alter().
 */
function media_folders_entity_form_display_alter(EntityFormDisplayInterface &$form_display, array $context) {
  if (isset($context['entity_type']) && $context['entity_type'] == 'media' && isset($context['bundle']) && !empty(\Drupal::request()->query->get('media-folders-edit'))) {
    $entity_display_repo = \Drupal::service('entity_display.repository');
    $form_display = $entity_display_repo->getFormDisplay($context['entity_type'], $context['bundle'], \Drupal::request()->query->get('media-folders-edit'));
  }
}
