<?php

/**
 * @file
 * Contains install and update functions for Backstop Generator module.
 */

/**
 * Implements hook_install().
 */
function backstop_generator_install() {
  // Use the service to create viewport entities for the default theme.
  $default_theme = \Drupal::config('system.theme')->get('default');
  \Drupal::service('backstop_generator.viewport_generator')->createViewportsForTheme($default_theme);
}
