<?php

/**
 * Implements hook_help().
 */

use Drupal\ckeditor5_markdown_editor\AssetManager;
use Drupal\Core\Render\Markup;
use Drupal\Core\Url;

/**
* Implements hook_library_info_alter().
*/

function ckeditor5_markdown_editor_library_info_alter (&$libraries, $extension): void {
  if ($extension === 'ckeditor5' && isset($libraries['internal.drupal.ckeditor5'])) {
    // Get all text formats with ckeditor5 as configured editor.
    $configEditors = \Drupal::service('config.storage')->listAll('editor.editor');
    foreach ($configEditors as $editor) {
      // Check if markdown_format is set to true in the plugin settings of the editor.
      if (\Drupal::config($editor)->get('settings.plugins.ckeditor5_markdown_editor_markdown_gfm.markdown_output')) {
        $libraries['internal.drupal.ckeditor5']['dependencies'][] = 'ckeditor5_markdown_editor/markdown_plugin';
        break;
      }
    }
  }
}

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 */
function ckeditor5_markdown_editor_ckeditor5_plugin_info_alter(array &$plugins) {
  $version = AssetManager::getPluginsVersion(\Drupal::service('library.discovery'), \Drupal::service('config.factory'));
  $plugin_statuses = AssetManager::getPluginsInstallStatuses($version);

  $all_installed = array_reduce($plugin_statuses, function ($acc, $plugin_status) {
    if ($acc && $plugin_status == FALSE) {
      $acc = $plugin_status;
    }

    return $acc;
  }, TRUE);

  $uninstalled_plugins = [];
  foreach ($plugin_statuses as $plugin_name => $is_installed) {
    if (!$all_installed && !empty($plugins[$plugin_name])) {
      unset($plugins[$plugin_name]);
    }

    if (!$is_installed) {
      $uninstalled_plugins[] = $plugin_name;
    }
  }

  if (!$all_installed) {
    \Drupal::logger('ckeditor5_markdown_editor')->error('The following plugins are missing: @uninstalled_plugins. <br />@install_message', [
      '@uninstalled_plugins' => implode(', ', $uninstalled_plugins),
      '@install_message' => _ckeditor5_markdown_editor_get_install_instructions(FALSE),
    ]);
  }
}

function ckeditor5_markdown_editor_library_info_build() {
  $libraryDiscovery = \Drupal::service('library.discovery');
  $configFactory = \Drupal::configFactory();
  $packageVersion = AssetManager::getCKEditorVersion($libraryDiscovery, $configFactory);

  $libraries = [];
  foreach (AssetManager::getPlugins($packageVersion) as $plugin) {
    $libraries[$plugin] = [
      'dependencies' => [
        'ckeditor5/ckeditor5'
      ],
      'js' => [
        AssetManager::getCKEditorLibraryPluginPath() . $plugin . '/build/' . $plugin . '.js' => [
          'preprocess' => FALSE,
          'minified' => TRUE,
          'type' => 'external',
        ]
      ]
    ];
  }
  return $libraries;
}

/**
 * Retrieve the install instructions message.
 *
 * @param bool $prefix
 *   (Optional) Determine if the prefix should be prepended to the install
 *   message. Defaults to true.
 *
 * @return string|\Drupal\Component\Render\MarkupInterface
 *   A safe string representation of the install instructions.
 */
function _ckeditor5_markdown_editor_get_install_instructions($prefix = TRUE, $update = FALSE) {
  $message_prefix = '';

  if ($prefix) {
    $message_prefix = t('The required CKEditor plugs are missing.');
  }

  return Markup::Create(t('@prefix To :op the CKEditor plugins run <strong><code>drush ckeditor5_markdown_editor::op</code></strong> if you have <a href=":drush" target="_blank">Drush</a> installed. Otherwise, please see the <a href=":project_page" target="_blank">installation instructions</a> on the page for additional :op methods.',
    [
      ':op' => $update ? 'update' : 'install',
      ':drush' => Url::fromUri('https://drush.org/', ['absolute' => TRUE])->toString(),
      ':project_page' => Url::fromUri('https://www.drupal.org/project/ckeditor_markdown_editor', ['absolute' => TRUE, 'fragment' => 'ckeditor-markdown-editor-install'])->toString(),
      '@prefix' => $message_prefix,
    ]
  ));
}
