<?php

/**
 * @file
 * Hook implementations for the Entity Usage Explorer module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function entity_usage_explorer_theme() {
  return [
    'entity_usage_overview' => [
      'template' => 'entity-usage-overview-page',
      'variables' => [
        'target_entity_type' => NULL,
        'target_entity_id' => NULL,
        'data' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function entity_usage_explorer_views_data() {
  $data['views']['table']['group'] = t('Entity Usage');
  $data['views']['table']['join'] = [
    '#global' => [],
  ];

  $data['views']['base_entity_usage_views_field'] = [
    'title' => t('Base Entity Usage'),
    'help' => t('Total count.'),
    'field' => [
      'id' => 'base_entity_usage_views_field',
    ],
  ];
  return $data;
}

/**
 * Implements hook_entity_operation().
 */
function entity_usage_explorer_entity_operation(EntityInterface $entity) {
  $operations = [];

  $account = \Drupal::currentUser();
  if ($account->hasPermission('access entity usage dashboard') && $entity instanceof ContentEntityInterface) {
    $operations['entity_usage_explorer'] = [
      'title' => t('Usage'),
      'weight' => '100',
      'url' => Url::fromRoute('entity_usage_explorer.usage_page', [
        'entity_type' => $entity->getEntityTypeId(),
        'entity_id' => $entity->id(),
      ]),
    ];
  }

  return $operations;
}
