<?php

/**
 * @file
 * This module cleans up data left over when a module is uninstalled.
 */

use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function module_cleanup_help($route_name) {
  switch ($route_name) {
    case 'help.page.module_cleanup':
      $output = '<h3>' . t('Introduction') . '</h3>';

      $errorLink = Link::fromTextAndUrl(
        t('Drupal\Component\Plugin\Exception\PluginNotFoundException: The "paragraph" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 142 of /var/www/html/core/lib/Drupal/Core/Entity/EntityTypeManager.php)'),
        Url::fromUri('https://www.drupal.org/project/paragraphs/issues/3165612#comment-14625691', ['attributes' => ['target' => '_blank']])
      )->toString();

      $fieldPurgeBatch = Link::fromTextAndUrl(
        t('field_purge_batch()'),
        Url::fromUri('https://api.drupal.org/api/drupal/modules!field!field.crud.inc/function/field_purge_batch/7.x', ['attributes' => ['target' => '_blank']])
      )->toString();

      $output .= '<p>' . t('This module cleans up data left over when a module is uninstalled.') . '</p>';
      $output .= '<p>' . t('There are two sections in this module. One is a fix for Module "module_name" has an entry in the system.schema key/value storage.') . '</p>';
      $output .= '<p>' . t('The other is a fix for @errorLink', ['@errorLink' => $errorLink]) . '</p>';
      $output .= '<p>' . t('To fix the second error the module runs the same function cron runs. @$fieldPurgeBatch', ['@$fieldPurgeBatch' => $fieldPurgeBatch]) . '</p>';

      $installation = Url::fromUri('https://www.drupal.org/project/module_cleanup')->toString();

      $output .= '<h3>' . t('Installation') . '</h3>';
      $output .= '<p>' . t('Installation instructions: <a href=":installation" target="_blank">Installation Instructions</a>', [':installation' => $installation]) . '</p>';

      $output .= '<h3>' . t('Requirements') . '</h3>';
      $output .= '<p>' . t('A Drupal site installed via composer.') . "</p>";

      $output .= '<h3>' . t('Drush Commands') . '</h3>';
      $output .= '<p>Command: <b>modcup:delete-config</b>: ' . t('Deletes left over data after a module is uninstalled. One required parameter. Parameter is the module machine name.') . "</p>";
      $output .= '<p>Alias: <b>modcup-dc</b>';
      $output .= '<br /><br />';
      $output .= '<p>Command: <b>modcup:field-purge-batch</b>: ' . t('Runs field_purge_batch(1000) only and outputs errors as messages.') . "</p>";
      $output .= '<p>Alias: <b>modcup-fpb</b>';
      $output .= '<br /><br />';
      $output .= '<p>Command: <b>modcup:create-storage</b>: ' . t('Creates a field storage only. Two required parameters. 1st parameter is the field name. 2nd parameter is the entity type.') . "</p>";
      $output .= '<p>Alias: <b>modcup-cs</b>';
      $output .= '<br /><br />';
      $output .= '<p>Command: <b>modcup:delete-field</b>: ' . t('Runs field_purge_batch(1000), creates a field storage if needed and then deletes the field and field storage. The module with the entity must be installed. Two required parameters. 1st parameter is the field name. 2nd parameter is the entity type.') . "</p>";
      $output .= '<p>Alias: <b>modcup-df</b>';
      return $output;

    default:
  }
}
