<?php

/**
 * @file
 * EPT Basic Button module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ept_basic_button_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ept_basic_button.
    case 'help.page.ept_basic_button':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('EPT modules provide ability to add different paragraphs in few clicks.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function ept_basic_button_preprocess_paragraph(&$variables) {
  if (empty($variables['elements']['#paragraph']) ||
    $variables['elements']['#paragraph']->bundle() !== 'ept_basic_button') {
    return;
  }

  $service = \Drupal::service('ept_basic_button.generate_custom_css');
  $ept_settings = $variables['elements']['#paragraph']->field_ept_settings->getValue();
  $paragraph_class = 'paragraph-id-' . $variables['elements']['#paragraph']->id();
  $variables['button_styles'] = $service->generateFromSettings($ept_settings[0]['ept_settings'], $paragraph_class);
}
