<?php

/**
 * @file
 * Hook implementations for the Pathauto Update module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\path_alias\PathAliasInterface;

/**
 * Implements hook_entity_update().
 */
function pathauto_update_entity_update(EntityInterface $entity): void {
  \Drupal::getContainer()
    ->get('pathauto_update.menu_link_content.subscriber')
    ->onMenuLinkUpdate($entity);

  \Drupal::getContainer()
    ->get('pathauto_update.path_alias_dependency_update.subscriber')
    ->onEntityUpdate($entity);

  if ($entity instanceof PathAliasInterface) {
    \Drupal::getContainer()
      ->get('pathauto_update.path_alias_update.subscriber')
      ->onPathAliasUpdate($entity);
  }
}

/**
 * Implements hook_entity_insert().
 */
function pathauto_update_entity_insert(EntityInterface $entity): void {
  \Drupal::getContainer()
    ->get('pathauto_update.menu_link_content.subscriber')
    ->onMenuLinkUpdate($entity);

  \Drupal::getContainer()
    ->get('pathauto_update.path_alias_dependency_update.subscriber')
    ->onEntityUpdate($entity);

  if ($entity instanceof PathAliasInterface) {
    \Drupal::getContainer()
      ->get('pathauto_update.path_alias_update.subscriber')
      ->onPathAliasUpdate($entity);
  }
}

/**
 * Implements hook_entity_translation_insert().
 */
function pathauto_update_entity_translation_insert(EntityInterface $translation): void {
  \Drupal::getContainer()
    ->get('pathauto_update.menu_link_content.subscriber')
    ->onMenuLinkUpdate($translation);

  \Drupal::getContainer()
    ->get('pathauto_update.path_alias_dependency_update.subscriber')
    ->onEntityUpdate($translation);

  if ($translation instanceof PathAliasInterface) {
    \Drupal::getContainer()
      ->get('pathauto_update.path_alias_update.subscriber')
      ->onPathAliasUpdate($translation);
  }
}

/**
 * Implements hook_entity_delete().
 */
function pathauto_update_entity_delete(EntityInterface $entity): void {
  \Drupal::getContainer()
    ->get('pathauto_update.path_alias_dependency_delete.subscriber')
    ->onEntityDelete($entity);
}
